server:
  port: 8080

spring:
  application:
    name: smartbill
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration